apiVersion: v1
data:
  database-name: b2Rvbw==
  database-password: b2Rvbw==
  database-user: b2Rvbw==
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  creationTimestamp: null
  labels:
    app: postgresql-persistent
    template: postgresql-persistent-template
  name: db
  selfLink: /api/v1/namespaces/web/secrets/db
type: Opaque
